version: '3.3'

services:
  
  web:
    build: ./roit-api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./roit-api:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./roit-api/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  minio:
        container_name: minio
        build: ./minio
        volumes:
            - ./minio/data:/data
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
            - DEFAULT_BUCKET=${MINIO_DEFAULT_BUCKET}
        command: server --console-address ":9001" /data

  pipe-db:
        build: 
          context: ./roit-pipe/db
          dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
          - 8080
        environment:
          - MYSQL_ROOT_PASSWORD: pass